### ISSUE TITLE
Lauching on macosx not working

### ISSUE THREAD

**Issue by peterkir** [A7exSchin/EclipseInstallationManager#21]
Due to the other filesystem layout on macosx...

`06:58:45.051 [main] DEBUG impl.EIMServiceImpl - Installation path is /Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse
06:58:45.053 [main] DEBUG impl.EIMServiceImpl - Workspace path is /Users/pekirsc/idefix/klibio-example-bnd-rcp/ws
06:58:45.055 [main] DEBUG impl.EIMServiceImpl - Starting /Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse/eclipse.exe in working directory /Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse with arguments
 [ws=/Users/pekirsc/idefix/klibio-example-bnd-rcp/ws]
06:58:45.116 [main] ERROR impl.EIMServiceImpl - There was a problem starting the the process!
Command: /Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse/eclipse.exe
Cannot run program "/Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse/eclipse.exe" (in directory "/Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse"): error=2, No such file or directory
java.io.IOException: Cannot run program "/Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse/eclipse.exe" (in directory "/Users/pekirsc/idefix/klibio-example-bnd-rcp/Eclipse.app/Contents/Eclipse"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at impl.EIMServiceImpl.startProcess(EIMServiceImpl.java:68)
        at impl.EIMServiceImpl.startEntry(EIMServiceImpl.java:97)
        at tray.impl.TrayApplication.lambda$createDisplay$4(TrayApplication.java:82)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
        at tray.impl.TrayApplication.createDisplay(TrayApplication.java:106)
        at tray.impl.TrayApplication.activate(TrayApplication.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:531)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1002)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:975)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:671)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:310)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:593)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:74)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:460)
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
        at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:139)
        at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:49)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.BundleTracker.open(BundleTracker.java:159)
        at org.apache.felix.scr.impl.AbstractExtender.startTracking(AbstractExtender.java:100)
        at org.apache.felix.scr.impl.AbstractExtender.doStart(AbstractExtender.java:92)
        at org.apache.felix.scr.impl.Activator.doStart(Activator.java:230)
        at org.apache.felix.scr.impl.AbstractExtender.start(AbstractExtender.java:72)
        at org.apache.felix.scr.impl.Activator.restart(Activator.java:197)
        at org.apache.felix.scr.impl.config.ScrConfigurationImpl.configure(ScrConfigurationImpl.java:234)
        at org.apache.felix.scr.impl.config.ScrConfigurationImpl.start(ScrConfigurationImpl.java:126)
        at org.apache.felix.scr.impl.Activator.start(Activator.java:127)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
        at aQute.launcher.Launcher.start(Launcher.java:699)
        at aQute.launcher.Launcher.startBundles(Launcher.java:679)
        at aQute.launcher.Launcher.activate(Launcher.java:585)
        at aQute.launcher.Launcher.launch(Launcher.java:404)
        at aQute.launcher.Launcher.run(Launcher.java:186)
        at aQute.launcher.Launcher.main(Launcher.java:162)
        at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
        at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:119)
        at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 72 more`

**Comment by A7exSchin** [comment]
Fixed with #24 thanks for the collaboration!

**Comment by peterkir** [comment]
with 0.3.7

`12:25:23.694 [main] ERROR impl.EIMServiceImpl - There was a problem starting the the process!
Command: /Users/pekirsc/idefix/klibio-bootstrap-main/Eclipse.app/Contents
Cannot run program "/Users/pekirsc/idefix/klibio-bootstrap-main/Eclipse.app/Contents" (in directory "/Users/pekirsc/idefix/klibio-bootstrap-main/Eclipse.app"): error=13, Permission denied
java.io.IOException: Cannot run program "/Users/pekirsc/idefix/klibio-bootstrap-main/Eclipse.app/Contents" (in directory "/Users/pekirsc/idefix/klibio-bootstrap-main/Eclipse.app"): error=13, Permission denied
...
`

**Comment by A7exSchin** [comment]
Fixed with [v0.3.8](https://github.com/A7exSchin/EclipseInstallationManager/commit/9e320f441bafc16ba912ebe960f928dd074ae764)
